name: ATCS-project
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - pip:
      - numpy
      - tqdm
      - pandas
      - transformers
      - accelerate
      - bitsandbytes
      - nltk